- backend/src/main/java/com/back/global/security/SecurityConfig.java
> feat(be): cors 설정 & ci 테스트

- backend/.gitignore
- backend/build.gradle.kts
- backend/src/main/java/com/back/domain/member/controller/MemberV1Controller.java
- backend/src/main/java/com/back/domain/member/dto/MemberPasswordChangeDto.java
- backend/src/main/java/com/back/domain/member/dto/MemberRequestDto.java
- backend/src/main/java/com/back/domain/member/dto/MemberResponseDto.java
- backend/src/main/java/com/back/domain/member/dto/MemberUpdateDto.java
- backend/src/main/java/com/back/domain/member/entity/Member.java
- backend/src/main/java/com/back/domain/member/repository/MemberRepository.java
- backend/src/main/java/com/back/domain/member/service/MemberService.java
- backend/src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
> feat(be) : Member 도메인 및 CRUD 구현,  예외 일부 수정

- backend/src/main/java/com/back/domain/member/repository/MemberRepository.java
- backend/src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
> fix(BE): globalexception 복구,memberrepository 수정

- frontend/src/app/components/Navbar.tsx
- frontend/src/app/layout.tsx
> feat(fe): 네비게이션 바 구현, close #25

- frontend/src/app/components/MyPage.tsx
- frontend/src/app/components/ui/card.tsx
- frontend/src/components/ui/card.tsx
- frontend/src/lib/utils.ts
> 유저 페이지 일부 보완 & 요구사항에 맞게 수정. 추가 보완 필요.

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/components/AssetPage.tsx
- frontend/src/app/components/MyPage.tsx
- frontend/src/app/layout.tsx
- frontend/src/components/ui/chart.tsx
- shardcn 차트 추가
- 바로가기 사이드바 추가
- ui 정렬
> 유저 페이지 보완, close#68

- backend/src/main/java/com/back/domain/auth/controller/AuthController.java
- frontend/next.config.ts
- frontend/src/app/components/LoginPage.tsx
- frontend/src/app/components/MyPage.tsx
- frontend/src/app/components/Router.tsx
- frontend/src/app/components/SignupPage.tsx
- frontend/src/app/components/WelcomePage.tsx
- frontend/src/app/page.tsx
- frontend/src/lib/auth.js
1. 로그인/회원가입 API 연동 
로그인 API 연동 구현
회원가입 API 연동 구현
2. Conflict 해결
MyPage.tsx 파일의 merge conflict 해결
> (FE) 로그인,회원가입 API 연동

- backend/src/test/java/com/back/domain/member/controller/MemberV1ControllerTest.java
- frontend/src/app/components/SignupPage.tsx
> fix(FE): conflict message 제거

- backend/src/test/java/com/back/domain/auth/controller/AuthControllerTest.java
- backend/src/test/java/com/back/domain/member/controller/MemberV1ControllerTest.java
> feat(BE) 멤버,인증 테스트 추가

- frontend/src/app/components/LoginPage.tsx
- frontend/src/app/components/SignupPage.tsx
- frontend/src/lib/auth.js
- 로그인/회원가입 입력값 검증 구현
- 백엔드 API 응답 구조에 맞게 수정
> fix(FE): 로그인/회원가입 API 요청 개선

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/components/AccountRecoveryPage.tsx
- frontend/src/app/components/LoginPage.tsx
- frontend/src/app/components/SignupPage.tsx
- frontend/src/app/components/ui/card.tsx
- frontend/src/app/components/ui/tabs.tsx
- frontend/src/app/config/routes.tsx
1. 계정 찾기 기능
이름 + 전화번호로 계정 찾기
계정을 찾으면 동일 화면에서 계정 정보 표시 (이름, 이메일)
"다시 찾기" 또는 "비밀번호 재설정" 버튼 제공
2. 비밀번호 재설정 기능
이메일 + 이름 + 전화번호로 계정 확인
계정 확인 후 동일 화면에서 새 비밀번호 입력
새 비밀번호 + 비밀번호 확인 입력
3. 임시 구현
실제 이메일 발송 없이 화면에서 직접 처리
테스트용 웹사이트에 적합한 방식으로 구현
> feat(FE): 계정 복구 및 회원가입시 전화번호 추가

- frontend/src/app/components/MyPage.tsx
- frontend/src/app/components/Router.tsx
> fix(FE):로그인 오류 수정,로그아웃 임시 추가

- backend/src/main/java/com/back/domain/auth/controller/AuthController.java
- backend/src/main/java/com/back/domain/auth/dto/FindAccountRequestDto.java
- backend/src/main/java/com/back/domain/auth/dto/FindAccountResponseDto.java
- backend/src/main/java/com/back/domain/auth/dto/LogoutResponseDto.java
- backend/src/main/java/com/back/domain/auth/dto/ResetPasswordRequestDto.java
- backend/src/main/java/com/back/domain/auth/dto/ResetPasswordResponseDto.java
- backend/src/main/java/com/back/domain/auth/service/AuthService.java
- backend/src/main/java/com/back/domain/member/repository/MemberRepository.java
- backend/src/main/java/com/back/domain/member/service/MemberService.java
- backend/src/test/java/com/back/domain/auth/controller/AuthControllerTest.java
- frontend/src/app/components/AccountRecoveryPage.tsx
- frontend/src/app/components/LoginPage.tsx
- frontend/src/app/components/MyPage.tsx
- frontend/src/app/components/Router.tsx
- frontend/src/lib/auth.js
> 인증 API 추가 및 로그인 오류 수정 및 로그아웃 버튼 추가

- frontend/next.config.ts
- frontend/src/app/components/AssetPage.tsx
- frontend/src/app/components/MyPage.tsx
- frontend/src/app/config/routes.tsx
- 자산 관리 페이지 완료
- REST API
- UI
- 사용자 페이지 로직 개선 & 보완
> 사용자 페이지 보완 및 자산 관리 페이지 완료(구현 & REST API)

- frontend/src/app/components/MyPage.tsx
> fix(FE):충돌 해결

- frontend/src/app/components/MyPage.tsx
> fix(FE): logout button 복구

- backend/src/main/java/com/back/domain/asset/controller/ApiV1AssetController.java
- backend/src/main/java/com/back/domain/asset/service/AssetService.java
- backend/src/main/java/com/back/domain/member/controller/SnapshotController.java
- backend/src/main/java/com/back/domain/member/repository/SnapshotRepository.java
- backend/src/main/java/com/back/domain/member/service/SnapshotService.java
- backend/src/main/java/com/back/domain/transactions/controller/ApiV1AccountTransactionController.java
- backend/src/main/java/com/back/domain/transactions/controller/ApiV1TransactionController.java
- backend/src/main/java/com/back/domain/transactions/dto/CreateTransactionRequestDto.java
- backend/src/main/java/com/back/domain/transactions/entity/Transaction.java
- backend/src/main/java/com/back/domain/transactions/service/AccountTransactionService.java
- backend/src/main/java/com/back/global/initData/BaseInitData.java
- backend/src/test/java/com/back/domain/transactions/controller/ApiV1TransactionControllerTest.java
- backend/src/test/java/com/back/domain/transactions/service/TransactionServiceTest.java
> 일부 변경사항에 맞게 수정

- backend/src/main/java/com/back/domain/account/service/AccountService.java
- backend/src/main/java/com/back/domain/asset/Dto/AssetDto.java
- backend/src/main/java/com/back/domain/asset/Dto/CreateAssetRequestDto.java
- backend/src/main/java/com/back/domain/asset/Dto/UpdateAssetRequestDto.java
- backend/src/main/java/com/back/domain/asset/entity/Asset.java
- backend/src/main/java/com/back/domain/member/controller/SnapshotController.java
- backend/src/main/java/com/back/domain/member/dto/SnapshotResponse.java
- backend/src/main/java/com/back/domain/member/entity/Snapshot.java
- backend/src/main/java/com/back/domain/member/service/SnapshotService.java
- backend/src/main/java/com/back/domain/transactions/dto/AccountTransactionDto.java
- backend/src/main/java/com/back/domain/transactions/dto/CreateAccTracRequestDto.java
- backend/src/main/java/com/back/domain/transactions/dto/CreateTransactionRequestDto.java
- backend/src/main/java/com/back/domain/transactions/dto/TransactionDto.java
- backend/src/main/java/com/back/domain/transactions/dto/UpdateTransactionRequestDto.java
- backend/src/main/java/com/back/domain/transactions/entity/AccountTransaction.java
- backend/src/main/java/com/back/domain/transactions/entity/Transaction.java
- backend/src/main/java/com/back/global/initData/BaseInitData.java
- backend/src/test/java/com/back/domain/account/controller/ApiV1AccountControllerTest.java
- backend/src/test/java/com/back/domain/asset/controller/ApiV1AssetControllerTest.java
- backend/src/test/java/com/back/domain/transactions/controller/ApiV1TransactionControllerTest.java
- backend/src/test/java/com/back/domain/transactions/service/TransactionServiceTest.java
- Asset: int assetValue => Long assetValue
- Transaction: int amount => Long amount
- AccountTransaction: int amount => Long amount
- 엔티티, 레포지, 서비스, 컨트롤러 모두 리팩토링
close #128 
close #130
> Asset, Transaction value 자료형 Long으로 수정. close#128, close#130

- frontend/src/app/components/ui/styles.tsx
- 자산의 증감률을 나타내는 블럭을 자산 변화 추이 그래프에 추가했습니다.
> feat(fe): 이전 월 대비 자산 증감률 표기 기능 추가

- frontend/src/app/components/AssetPage.tsx
- frontend/src/app/components/CreateAssetModal.tsx
- /api/v1/members/me를 통한 memberId를 불러오는 과정을 제거하여 백엔드 서버에 보내는 API 요청 수 감소
- memberId를 가져오지 않기 때문에, 새로 추가된 API를 통해 기존의 로직 구현.
> feat(fe): 로그인 된 사용자의 memberId를 받아오는 API 제거, 추가된 API에 맞게 로직 변경.

- frontend/src/app/components/AssetDetailPage.tsx
- frontend/src/app/components/CreateAssetModal.tsx
- frontend/src/app/components/CreateTransactionModal.tsx
- AssetDetailePage, CreateAssetModal, CreateTransactionModal의 디버깅 로그 제거.
> fix(fe): 일부 디버깅 로그들 삭제

- backend/.claude/settings.local.json
- backend/src/main/java/com/back/domain/auth/controller/AuthController.java
- backend/src/main/java/com/back/domain/auth/dto/LoginRequestDto.java
- backend/src/main/java/com/back/domain/auth/dto/TokenPairDto.java
- backend/src/main/java/com/back/domain/auth/entity/RefreshToken.java
- backend/src/main/java/com/back/domain/auth/repository/RefreshTokenRepository.java
- backend/src/main/java/com/back/domain/auth/service/AuthService.java
- backend/src/main/java/com/back/domain/member/controller/MemberV1Controller.java
- backend/src/main/java/com/back/domain/member/dto/MemberPasswordChangeDto.java
- backend/src/main/java/com/back/domain/member/dto/MemberRequestDto.java
- backend/src/main/java/com/back/domain/member/dto/MemberUpdateDto.java
- backend/src/main/java/com/back/domain/member/service/MemberService.java
- backend/src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
- backend/src/main/java/com/back/global/security/SecurityConfig.java
- backend/src/main/java/com/back/global/security/jwt/JwtUtil.java
- backend/src/main/java/com/back/global/security/service/RateLimitService.java
- backend/src/test/java/com/back/domain/auth/controller/AuthControllerTest.java
- backend/src/test/java/com/back/domain/goal/controller/ApiV1GoalControllerTest.java
- backend/src/test/java/com/back/domain/member/controller/MemberV1ControllerTest.java
- backend/src/test/java/com/back/domain/transactions/controller/AccountTransactionControllerTest.java
- frontend/src/app/components/AccountRecoveryPage.tsx
- frontend/src/app/components/LoginPage.tsx
- frontend/src/app/components/MyPage.tsx
- frontend/src/app/components/Router.tsx
- frontend/src/app/components/SignupPage.tsx
- frontend/src/app/lib/backend/client.ts
- frontend/src/lib/auth.js
전체 개선 항목 (9개)
보안 개선 (4개)
1.  비밀번호 변경시 기존 비밀번호 확인 추가
2.  Controller에서 직접 Repository 접근 제거 (계층 구조 개선)
3.  Exception 처리 일관성 확보 (전역 예외 처리)
4.  계정 찾기/비밀번호 재설정 보안 강화 (IP별 시도 제한)
기능 개선 (3개)
5.  DTO 검증 강화 (입력값 검증 완성)
6.  권한 기반 접근제어 완성 (ADMIN/USER 역할 구분)
7.  로그아웃 로깅 추가 (보안 추적)
신규 기능 (2개)
8.  Refresh Token 시스템 구현 (자동 토큰 갱신)
9.  Rate Limiting 시스템 (무차별 대입 공격 방지)
> feat: 기타 오류 개선 및 refreshToken 추가

- frontend/src/app/components/Navbar.tsx
- frontend/src/app/components/ProfilePage.tsx
- frontend/src/app/components/ui/card.tsx
- frontend/src/app/config/routes.tsx
> feat(fe): 사용자정보 페이지 추가

- backend/src/main/java/com/back/domain/account/controller/ApiV1AccountController.java
- backend/src/main/java/com/back/domain/account/entity/Account.java
- backend/src/main/java/com/back/domain/account/exception/AccountNotFoundException.java
- backend/src/main/java/com/back/domain/account/service/AccountService.java
- backend/src/main/java/com/back/global/dto/ErrorResponse.java
- backend/src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
- backend/src/test/java/com/back/domain/account/controller/ApiV1AccountControllerTest.java
추가 수정 및 구현 사항
-커스텀 예외 처리
-에러응답의 일관성을 위해 global dto 생성
-예외 발생시 로그 출력
-테스트케이스 수정
> feat(be) : account hard delete -> soft delete 방식으로 전환

- frontend/src/app/admin/page.tsx
- frontend/src/app/components/SideBar.tsx
- frontend/src/app/mypage/notices/[noticeId]/page.tsx
- frontend/src/app/mypage/notices/page.tsx
> feat: admin 페이지에 공지사항 버튼 추가
